### ISSUE TITLE
Dataset downloading problem 

### ISSUE THREAD

**Issue by woojoo520** [karolzak/support-tickets-classification#20]
Hi,

Thank you so much for creating such an awesome resource! :)
But I have some problem downloading the dataset:
"urllib.error.HTTPError: HTTP Error 409: Public access is not permitted on this storage account."
I would be very grateful if you could help me with this problem.

Regards,

woojoo

**Comment by karolzak** [comment]
Hi @woojoo520 ,
Thanks for your interest in this project and following up via email.
Some time ago I had to take down the dataset from public access due to some internal policies.
Now I will only be sharing the dataset on per request basis.

**Comment by arsalanm001** [comment]
Hi @karolzak,

I am a Data Science student, I found this project is very interesting, I wanted to learn by working on this project. Since the dataset is not accessible I couldn't explore this project. So could you please give access to the dataset.

Regards 

Arsalan
