### ISSUE TITLE
Data cleansing datasets

### ISSUE THREAD

**Issue by Mikw777** [karolzak/Support-Tickets-Classification#3]
Hello, thanks for sharing this interesting project!
Looking at your code in 0_preprocess_data.py, you use a number of datasets for data cleansing, like the dataset of EnglishWords, FirstNames or yet WordsBlackList.
Would you share how you populated these datasets or might be provide some examples?
Thanks & regards, Michael.

**Comment by karolzak** [comment]
Hi @Mikw777 !
Thanks for stoping by! Good to hear that you enjoy our little project :)

So the datasets I used for data cleansing are simply a collection of words that should be used or removed from our dataset. I found inspiration for these datasets somewhere in the internet.

Just few minutes ago I commited [EnglishWords](https://github.com/karolzak/Support-Tickets-Classification/blob/master/datasets/CSV_Database_of_First_Names.csv) and [FirstNames](https://github.com/karolzak/Support-Tickets-Classification/blob/master/datasets/wordsEn.txt) datasets so you can check them out on your own.
As for the WordsBlackList dataset, unfortunately I cannot share it as it consists Endavas private information.

Hope it helps!
Karol
