### ISSUE TITLE
Webservice aint running

### ISSUE THREAD

**Issue by rsingh2083** [karolzak/support-tickets-classification#4]
The webservice starts at localhost:5555 but the only think I can see is : -

```
Hello, World!
This is a sample web service written in Python using Flask module.
```
Where do I even go from here ?

**Comment by karolzak** [comment]
Hi @rsingh2083 

That really depends on what do you want achieve :)
The message you see is perfectly fine and it's like an index page for the web service.
Now depending on what kind of "routes" you have coded you can access different methods using those routes, i.e.:
```
http://localhost:5555/your/custom/route_name
```


This address would give you access to the piece of code below:

```python
@app.route('/your/custom/route_name', methods=['POST'])
def your_method():
    file_upload = request.files['file']
    if file_upload:
        temp_file_path=os.path.join('./Temp',str(uuid.uuid4())+'.jpg')
        file_upload.save(temp_file_path)
        app.logger.debug('File is saved as %s', temp_file_path)
        ...
        ...
```

I strongly advise going through some sort of Flask tutorial for more details on how it works.
